### ISSUE TITLE
Malware Detected

### ISSUE THREAD

**Issue by wayne-jfl** [meganutmega/img2ico#1]
On-Access scanning has detected malicious behavior on img2ico-0.3.0.zip and identified it as Heur.BZC.ONG.Boxter.241.E186A0EC.
BitDefender Business Premium

**Comment by xTerrene** [comment]
After looking through BitDefender's various forum posts regarding Heur.BZC._xxx_.Boxter._yyy_._zzzzzzzz_, we're 100% certain this is being false flagged due to how img2ico works.

In order to ensure it works, img2ico downloads and opens the ImageMagick program for you, then uses its commands to convert everything. Because of this, however, it's technically downloading and running an executable "without your permission", which may be flagged by antiviruses as malicious.

We can assure you that img2ico is safe. The ZIP file you get is an executable (which admittedly doesn't work -- we're working on that), the batch file the executable _should_ be running, and a few PowerShell scripts that are needed to get file/directory choosing working. Anything with in the [child img2ico folder](https://github.com/meganutmega/img2ico/tree/main/img2ico) is what would be downloaded.

**Comment by EarthToAccess** [comment]
problem regarding img2ico's internal installation of ImageMagick flagging BitDefender
